### ISSUE TITLE
Action is failing.  Are you going to fix it?

### ISSUE THREAD

**Issue by jbrucker** [Phukit-Time/demo-pyci#1]
Your action for code coverage is failing, and there's no badge from Codecov.io.
Are you going to fix this?

On Github, you do not need to use the `-t` option to codecov.
Indeed, you don't need to download and run the "codecov" binary at all
because Github provides an action for that:
```
    -name: upload coverage data to Codecov
     uses: codecov/codecov-action@v3
```

**Comment by Phukit-Time** [comment]
I'm trying to fix it.

**Comment by Phukit-Time** [comment]
I fixed it, can you check again. thank you.

**Comment by jbrucker** [comment]
Looks much better now.
